FROM node:20-alpine

WORKDIR /srv
RUN apk add --no-cache bash python3 make g++ libc6-compat curl

COPY docker-entrypoint.sh /usr/local/bin/strapi-entrypoint
RUN chmod +x /usr/local/bin/strapi-entrypoint

ENV APP_DIR=/srv/app
EXPOSE 1337

ENTRYPOINT ["strapi-entrypoint"]
CMD ["develop"]


